version: '2'
services:
    api:
        # Uses Dockerfile in 'api'
        build: api
        ports:
        # Fowards host port to 'api'
        - "3000:3000"
        links: 
        # Links 'mongo' container to 'api'
        - mongo
        volumes:
        - /logs:/logs
    web:
        # Uses Dockerfile in 'web'
        build: web
        ports:
        # Fowards host port to 'web'
        - "8080:8080"
    mongo:
        # Uses mongo image from Docker hub
        image: "mongo"
    mongo-seed:
        # Uses Dockerfile in 'mongo-seed'
        build: mongo-seed
        links:
            - mongo